-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2014.2
-- Copyright (C) 2014 Xilinx Inc. All rights reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity demod_mux_VHTLTFRefInv_21_V_rom is 
    generic(
             dwidth     : integer := 7; 
             awidth     : integer := 8; 
             mem_size    : integer := 234
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of demod_mux_VHTLTFRefInv_21_V_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 => "1100000", 1 to 2=> "0100000", 3 to 5=> "1100000", 6 to 7=> "0100000", 
    8 => "1100000", 9 => "0100000", 10 => "1100000", 11 => "0100000", 
    12 to 17=> "1100000", 18 to 19=> "0100000", 20 to 21=> "1100000", 22 => "0100000", 
    23 => "1100000", 24 => "0100000", 25 to 30=> "1100000", 31 to 32=> "0100000", 
    33 to 34=> "1100000", 35 to 36=> "0100000", 37 => "1100000", 38 to 42=> "0100000", 
    43 to 44=> "1100000", 45 to 46=> "0100000", 47 => "1100000", 48 => "0100000", 
    49 => "1100000", 50 => "0100000", 51 to 54=> "1100000", 55 to 57=> "0100000", 
    58 to 59=> "1100000", 60 => "0100000", 61 => "1100000", 62 => "0100000", 
    63 to 64=> "1100000", 65 => "0100000", 66 to 67=> "1100000", 68 to 69=> "0100000", 
    70 => "1100000", 71 => "0100000", 72 => "1100000", 73 => "0100000", 
    74 to 79=> "1100000", 80 to 81=> "0100000", 82 to 83=> "1100000", 84 => "0100000", 
    85 => "1100000", 86 => "0100000", 87 to 92=> "1100000", 93 to 94=> "0100000", 
    95 to 96=> "1100000", 97 to 98=> "0100000", 99 => "1100000", 100 to 104=> "0100000", 
    105 to 106=> "1100000", 107 to 108=> "0100000", 109 => "1100000", 110 => "0100000", 
    111 => "1100000", 112 => "0100000", 113 to 118=> "1100000", 119 to 120=> "0100000", 
    121 to 122=> "1100000", 123 => "0100000", 124 => "1100000", 125 => "0100000", 
    126 to 131=> "1100000", 132 to 133=> "0100000", 134 to 136=> "1100000", 137 => "0100000", 
    138 to 143=> "1100000", 144 to 145=> "0100000", 146 to 147=> "1100000", 148 => "0100000", 
    149 => "1100000", 150 => "0100000", 151 => "1100000", 152 to 156=> "0100000", 
    157 to 158=> "1100000", 159 to 160=> "0100000", 161 => "1100000", 162 to 163=> "0100000", 
    164 to 167=> "1100000", 168 to 170=> "0100000", 171 to 172=> "1100000", 173 => "0100000", 
    174 => "1100000", 175 => "0100000", 176 to 177=> "1100000", 178 => "0100000", 
    179 to 180=> "1100000", 181 to 182=> "0100000", 183 to 184=> "1100000", 185 => "0100000", 
    186 => "1100000", 187 => "0100000", 188 to 193=> "1100000", 194 to 195=> "0100000", 
    196 to 198=> "1100000", 199 => "0100000", 200 to 205=> "1100000", 206 to 207=> "0100000", 
    208 to 209=> "1100000", 210 => "0100000", 211 => "1100000", 212 => "0100000", 
    213 => "1100000", 214 to 218=> "0100000", 219 to 220=> "1100000", 221 to 222=> "0100000", 
    223 => "1100000", 224 to 225=> "0100000", 226 to 230=> "1100000", 231 => "0100000", 
    232 => "1100000", 233 => "0100000" );


attribute EQUIVALENT_REGISTER_REMOVAL : string;
begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity demod_mux_VHTLTFRefInv_21_V is
    generic (
        DataWidth : INTEGER := 7;
        AddressRange : INTEGER := 234;
        AddressWidth : INTEGER := 8);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of demod_mux_VHTLTFRefInv_21_V is
    component demod_mux_VHTLTFRefInv_21_V_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;




begin
    demod_mux_VHTLTFRefInv_21_V_rom_U :  component demod_mux_VHTLTFRefInv_21_V_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


