-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2014.2
-- Copyright (C) 2014 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity DownResample is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    input_V : IN STD_LOGIC_VECTOR (35 downto 0);
    input_V_ap_vld : IN STD_LOGIC;
    output_real_V_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_real_V_ce0 : OUT STD_LOGIC;
    output_real_V_we0 : OUT STD_LOGIC;
    output_real_V_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    output_imag_V_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    output_imag_V_ce0 : OUT STD_LOGIC;
    output_imag_V_we0 : OUT STD_LOGIC;
    output_imag_V_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    DDC_freq_norm_0_V : IN STD_LOGIC_VECTOR (31 downto 0);
    DDC_freq_norm_1_V : IN STD_LOGIC_VECTOR (31 downto 0);
    FreqOffsetIn_V : IN STD_LOGIC_VECTOR (24 downto 0) );
end;


architecture behav of DownResample is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "DownResample,hls_ip_2014_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7k480tffg1156-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.150000,HLS_SYN_LAT=12,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_pp0_stg0_fsm_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_true : BOOLEAN := true;
    constant ap_const_lv36_0 : STD_LOGIC_VECTOR (35 downto 0) := "000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv27_93 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000010010011";
    constant ap_const_lv30_3FFFFC5B : STD_LOGIC_VECTOR (29 downto 0) := "111111111111111111110001011011";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_D69 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000110101101001";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv34_3FFFFD816 : STD_LOGIC_VECTOR (33 downto 0) := "1111111111111111111101100000010110";
    constant ap_const_lv34_9D93 : STD_LOGIC_VECTOR (33 downto 0) := "0000000000000000001001110110010011";

    signal input_V_in_sig : STD_LOGIC_VECTOR (35 downto 0);
    signal input_V_preg : STD_LOGIC_VECTOR (35 downto 0) := "000000000000000000000000000000000000";
    signal input_V_ap_vld_in_sig : STD_LOGIC;
    signal input_V_ap_vld_preg : STD_LOGIC := '0';
    signal phaseAcc_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal cosT_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal cosT_V_ce0 : STD_LOGIC;
    signal cosT_V_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal cosT_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal cosT_V_ce1 : STD_LOGIC;
    signal cosT_V_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sinT_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal sinT_V_ce0 : STD_LOGIC;
    signal sinT_V_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal sinT_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sinT_V_ce1 : STD_LOGIC;
    signal sinT_V_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal reg_real_V_8 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_imag_V_8 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_real_V_6 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_imag_V_6 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_real_V_4 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_imag_V_4 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_real_V_2 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_imag_V_2 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_real_V_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_imag_V_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_real_V_17 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_imag_V_17 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_real_V_15 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_imag_V_15 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_real_V_13 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_imag_V_13 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_real_V_11 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_imag_V_11 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_real_V_9 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_imag_V_9 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_real_V_7 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_imag_V_7 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_real_V_5 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_imag_V_5 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_real_V_3 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_imag_V_3 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_real_V_1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal reg_imag_V_1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal p_Result_s_reg_1241 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_reg_ppiten_pp0_it0 : STD_LOGIC;
    signal ap_reg_ppiten_pp0_it1 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it2 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it3 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it4 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it5 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it6 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it7 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it8 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it9 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it10 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it11 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it12 : STD_LOGIC := '0';
    signal tmp_2_fu_315_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_2_reg_1246 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_tmp_2_reg_1246_pp0_it1 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_tmp_2_reg_1246_pp0_it2 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Result_1_reg_1251 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_ppstg_p_Result_1_reg_1251_pp0_it1 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_ppstg_p_Result_1_reg_1251_pp0_it2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_ppstg_p_Result_1_reg_1251_pp0_it3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_ppstg_p_Result_1_reg_1251_pp0_it4 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_ppstg_p_Result_1_reg_1251_pp0_it5 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_ppstg_p_Result_1_reg_1251_pp0_it6 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_reg_ppstg_p_Result_1_reg_1251_pp0_it7 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_4_reg_1256 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_tmp_4_reg_1256_pp0_it1 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_tmp_4_reg_1256_pp0_it2 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_tmp_4_reg_1256_pp0_it3 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_tmp_4_reg_1256_pp0_it4 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_tmp_4_reg_1256_pp0_it5 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_tmp_4_reg_1256_pp0_it6 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_tmp_4_reg_1256_pp0_it7 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_tmp_4_reg_1256_pp0_it8 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_tmp_4_reg_1256_pp0_it9 : STD_LOGIC_VECTOR (17 downto 0);
    signal cosT_V_load_reg_1271 : STD_LOGIC_VECTOR (17 downto 0);
    signal sinT_V_load_reg_1276 : STD_LOGIC_VECTOR (17 downto 0);
    signal OP1_V_cast_fu_362_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_reg_ppstg_tmp_2_reg_1246_pp0_it2_temp: signed (18-1 downto 0);
    signal tmp_7_reg_1297 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_9_reg_1303 : STD_LOGIC_VECTOR (17 downto 0);
    signal reg_real_V_15_load_reg_1309 : STD_LOGIC_VECTOR (17 downto 0);
    signal reg_imag_V_15_load_reg_1314 : STD_LOGIC_VECTOR (17 downto 0);
    signal reg_real_V_13_load_reg_1319 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_real_V_13_load_reg_1319_pp0_it7 : STD_LOGIC_VECTOR (17 downto 0);
    signal reg_imag_V_13_load_reg_1324 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_imag_V_13_load_reg_1324_pp0_it7 : STD_LOGIC_VECTOR (17 downto 0);
    signal reg_real_V_11_load_reg_1329 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_real_V_11_load_reg_1329_pp0_it7 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_real_V_11_load_reg_1329_pp0_it8 : STD_LOGIC_VECTOR (17 downto 0);
    signal reg_imag_V_11_load_reg_1334 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_imag_V_11_load_reg_1334_pp0_it7 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_imag_V_11_load_reg_1334_pp0_it8 : STD_LOGIC_VECTOR (17 downto 0);
    signal reg_real_V_9_load_reg_1339 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_real_V_9_load_reg_1339_pp0_it7 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_real_V_9_load_reg_1339_pp0_it8 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_real_V_9_load_reg_1339_pp0_it9 : STD_LOGIC_VECTOR (17 downto 0);
    signal reg_imag_V_9_load_reg_1344 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_imag_V_9_load_reg_1344_pp0_it7 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_imag_V_9_load_reg_1344_pp0_it8 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_imag_V_9_load_reg_1344_pp0_it9 : STD_LOGIC_VECTOR (17 downto 0);
    signal reg_real_V_7_load_reg_1349 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_real_V_7_load_reg_1349_pp0_it7 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_real_V_7_load_reg_1349_pp0_it8 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_real_V_7_load_reg_1349_pp0_it9 : STD_LOGIC_VECTOR (17 downto 0);
    signal reg_imag_V_7_load_reg_1354 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_imag_V_7_load_reg_1354_pp0_it7 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_imag_V_7_load_reg_1354_pp0_it8 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_imag_V_7_load_reg_1354_pp0_it9 : STD_LOGIC_VECTOR (17 downto 0);
    signal reg_real_V_5_load_reg_1359 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_real_V_5_load_reg_1359_pp0_it7 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_real_V_5_load_reg_1359_pp0_it8 : STD_LOGIC_VECTOR (17 downto 0);
    signal reg_imag_V_5_load_reg_1364 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_imag_V_5_load_reg_1364_pp0_it7 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_imag_V_5_load_reg_1364_pp0_it8 : STD_LOGIC_VECTOR (17 downto 0);
    signal reg_real_V_3_load_reg_1369 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_real_V_3_load_reg_1369_pp0_it7 : STD_LOGIC_VECTOR (17 downto 0);
    signal reg_imag_V_3_load_reg_1374 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_reg_ppstg_reg_imag_V_3_load_reg_1374_pp0_it7 : STD_LOGIC_VECTOR (17 downto 0);
    signal reg_real_V_1_load_reg_1379 : STD_LOGIC_VECTOR (17 downto 0);
    signal reg_imag_V_1_load_reg_1384 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_598_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Val2_9_reg_1399 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_fu_621_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Val2_s_reg_1404 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_17_reg_1434 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_20_reg_1444 : STD_LOGIC_VECTOR (13 downto 0);
    signal cosT_V_load_1_reg_1449 : STD_LOGIC_VECTOR (17 downto 0);
    signal sinT_V_load_1_reg_1454 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_21_reg_1464 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_22_reg_1474 : STD_LOGIC_VECTOR (17 downto 0);
    signal OP1_V_cast_27_fu_900_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal ap_reg_ppstg_tmp_4_reg_1256_pp0_it9_temp: signed (18-1 downto 0);
    signal tmp_23_reg_1500 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_24_reg_1510 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_25_reg_1515 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_26_reg_1520 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_5_fu_357_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_15_1_fu_671_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Val2_7_fu_345_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_255_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_fu_265_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp1_fu_281_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_6_fu_287_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal FreqOffsetTmp_V_fu_273_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_265_p3_temp: signed (25-1 downto 0);
    signal p_Val2_3_1_fu_293_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_3_1_fu_293_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_6_fu_287_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_6_1_fu_299_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_4_fu_339_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_368_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_368_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_377_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_377_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_368_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_377_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal r_V_fu_588_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal reg_real_V_17_temp: signed (18-1 downto 0);
    signal r_V_fu_588_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_7_reg_1297_temp: signed (18-1 downto 0);
    signal r_V_fu_588_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_598_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_598_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_1_fu_611_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal reg_imag_V_17_temp: signed (18-1 downto 0);
    signal r_V_1_fu_611_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_9_reg_1303_temp: signed (18-1 downto 0);
    signal r_V_1_fu_611_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_621_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_621_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_0_1_fu_633_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal reg_real_V_15_load_reg_1309_temp: signed (18-1 downto 0);
    signal r_V_0_1_fu_633_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal reg_real_V_1_load_reg_1379_temp: signed (18-1 downto 0);
    signal r_V_0_1_fu_633_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_643_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_643_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_1_0_1_fu_655_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal reg_imag_V_15_load_reg_1314_temp: signed (18-1 downto 0);
    signal r_V_1_0_1_fu_655_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal reg_imag_V_1_load_reg_1384_temp: signed (18-1 downto 0);
    signal r_V_1_0_1_fu_655_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_665_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_665_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_8_fu_676_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_13_fu_694_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Val2_26_0_1_fu_706_p0 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_13_fu_694_p3_temp: signed (27-1 downto 0);
    signal grp_fu_643_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_12_fu_685_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_15_fu_712_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Val2_31_0_1_fu_724_p0 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_15_fu_712_p3_temp: signed (27-1 downto 0);
    signal grp_fu_665_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal r_V_0_2_fu_736_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_reg_ppstg_reg_real_V_13_load_reg_1319_pp0_it7_temp: signed (18-1 downto 0);
    signal r_V_0_2_fu_736_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_reg_ppstg_reg_real_V_3_load_reg_1369_pp0_it7_temp: signed (18-1 downto 0);
    signal r_V_0_2_fu_736_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_746_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_746_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_26_0_1_fu_706_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal r_V_1_0_2_fu_768_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_reg_ppstg_reg_imag_V_13_load_reg_1324_pp0_it7_temp: signed (18-1 downto 0);
    signal r_V_1_0_2_fu_768_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_reg_ppstg_reg_imag_V_3_load_reg_1374_pp0_it7_temp: signed (18-1 downto 0);
    signal r_V_1_0_2_fu_768_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_778_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_778_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_31_0_1_fu_724_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_18_fu_794_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_746_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_26_0_2_fu_809_p0 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_18_fu_794_p3_temp: signed (30-1 downto 0);
    signal p_Val2_26_0_2_fu_809_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_746_p2_temp: signed (32-1 downto 0);
    signal tmp_27_fu_815_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_778_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_31_0_2_fu_830_p0 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_27_fu_815_p3_temp: signed (30-1 downto 0);
    signal p_Val2_31_0_2_fu_830_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_778_p2_temp: signed (32-1 downto 0);
    signal r_V_0_3_fu_842_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_reg_ppstg_reg_real_V_11_load_reg_1329_pp0_it8_temp: signed (18-1 downto 0);
    signal r_V_0_3_fu_842_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_reg_ppstg_reg_real_V_5_load_reg_1359_pp0_it8_temp: signed (18-1 downto 0);
    signal r_V_0_3_fu_842_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_852_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_852_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Val2_26_0_2_fu_809_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal r_V_1_0_3_fu_874_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_reg_ppstg_reg_imag_V_11_load_reg_1334_pp0_it8_temp: signed (18-1 downto 0);
    signal r_V_1_0_3_fu_874_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_reg_ppstg_reg_imag_V_5_load_reg_1364_pp0_it8_temp: signed (18-1 downto 0);
    signal r_V_1_0_3_fu_874_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_884_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_884_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Val2_31_0_2_fu_830_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_906_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_906_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_915_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_915_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_60_0_3_fu_921_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_852_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_67_0_3_fu_934_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_884_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal r_V_0_4_fu_953_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_reg_ppstg_reg_real_V_9_load_reg_1339_pp0_it9_temp: signed (18-1 downto 0);
    signal r_V_0_4_fu_953_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_reg_ppstg_reg_real_V_7_load_reg_1349_pp0_it9_temp: signed (18-1 downto 0);
    signal r_V_0_4_fu_953_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_963_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_963_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_26_0_3_fu_928_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal r_V_1_0_4_fu_985_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_reg_ppstg_reg_imag_V_9_load_reg_1344_pp0_it9_temp: signed (18-1 downto 0);
    signal r_V_1_0_4_fu_985_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_reg_ppstg_reg_imag_V_7_load_reg_1354_pp0_it9_temp: signed (18-1 downto 0);
    signal r_V_1_0_4_fu_985_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_995_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_995_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_31_0_3_fu_941_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_60_0_4_fu_1011_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_963_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_67_0_4_fu_1024_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_995_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal p_Val2_26_0_4_fu_1018_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal p_Val2_31_0_4_fu_1031_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_906_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_915_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_11_fu_1185_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal p_Val2_8_fu_1177_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal p_Val2_10_fu_1192_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal tmp_16_fu_1217_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal p_Val2_11_fu_1209_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal p_Val2_12_fu_1224_p2 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_368_ce : STD_LOGIC;
    signal grp_fu_377_ce : STD_LOGIC;
    signal grp_fu_598_ce : STD_LOGIC;
    signal grp_fu_621_ce : STD_LOGIC;
    signal grp_fu_643_ce : STD_LOGIC;
    signal grp_fu_665_ce : STD_LOGIC;
    signal grp_fu_746_ce : STD_LOGIC;
    signal grp_fu_778_ce : STD_LOGIC;
    signal grp_fu_852_ce : STD_LOGIC;
    signal grp_fu_884_ce : STD_LOGIC;
    signal grp_fu_906_ce : STD_LOGIC;
    signal grp_fu_915_ce : STD_LOGIC;
    signal grp_fu_963_ce : STD_LOGIC;
    signal grp_fu_995_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_pprstidle_pp0 : STD_LOGIC;

    component DownResample_mul_18s_18s_34_3 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (33 downto 0) );
    end component;


    component DownResample_mul_19s_8ns_27_2 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (18 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (26 downto 0) );
    end component;


    component DownResample_mul_19s_11s_30_2 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (18 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component DownResample_mul_19s_12ns_32_2 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (18 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component DownResample_mul_19s_15s_34_2 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (18 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (33 downto 0) );
    end component;


    component DownResample_mul_19s_16ns_34_2 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (18 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (33 downto 0) );
    end component;


    component DownResample_cosT_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component DownResample_sinT_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    cosT_V_U : component DownResample_cosT_V
    generic map (
        DataWidth => 18,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => cosT_V_address0,
        ce0 => cosT_V_ce0,
        q0 => cosT_V_q0,
        address1 => cosT_V_address1,
        ce1 => cosT_V_ce1,
        q1 => cosT_V_q1);

    sinT_V_U : component DownResample_sinT_V
    generic map (
        DataWidth => 18,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => sinT_V_address0,
        ce0 => sinT_V_ce0,
        q0 => sinT_V_q0,
        address1 => sinT_V_address1,
        ce1 => sinT_V_ce1,
        q1 => sinT_V_q1);

    DownResample_mul_18s_18s_34_3_U0 : component DownResample_mul_18s_18s_34_3
    generic map (
        ID => 0,
        NUM_STAGE => 3,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_368_p0,
        din1 => grp_fu_368_p1,
        ce => grp_fu_368_ce,
        dout => grp_fu_368_p2);

    DownResample_mul_18s_18s_34_3_U1 : component DownResample_mul_18s_18s_34_3
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_377_p0,
        din1 => grp_fu_377_p1,
        ce => grp_fu_377_ce,
        dout => grp_fu_377_p2);

    DownResample_mul_19s_8ns_27_2_U2 : component DownResample_mul_19s_8ns_27_2
    generic map (
        ID => 2,
        NUM_STAGE => 2,
        din0_WIDTH => 19,
        din1_WIDTH => 8,
        dout_WIDTH => 27)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_598_p0,
        din1 => grp_fu_598_p1,
        ce => grp_fu_598_ce,
        dout => grp_fu_598_p2);

    DownResample_mul_19s_8ns_27_2_U3 : component DownResample_mul_19s_8ns_27_2
    generic map (
        ID => 3,
        NUM_STAGE => 2,
        din0_WIDTH => 19,
        din1_WIDTH => 8,
        dout_WIDTH => 27)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_621_p0,
        din1 => grp_fu_621_p1,
        ce => grp_fu_621_ce,
        dout => grp_fu_621_p2);

    DownResample_mul_19s_11s_30_2_U4 : component DownResample_mul_19s_11s_30_2
    generic map (
        ID => 4,
        NUM_STAGE => 2,
        din0_WIDTH => 19,
        din1_WIDTH => 11,
        dout_WIDTH => 30)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_643_p0,
        din1 => grp_fu_643_p1,
        ce => grp_fu_643_ce,
        dout => grp_fu_643_p2);

    DownResample_mul_19s_11s_30_2_U5 : component DownResample_mul_19s_11s_30_2
    generic map (
        ID => 5,
        NUM_STAGE => 2,
        din0_WIDTH => 19,
        din1_WIDTH => 11,
        dout_WIDTH => 30)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_665_p0,
        din1 => grp_fu_665_p1,
        ce => grp_fu_665_ce,
        dout => grp_fu_665_p2);

    DownResample_mul_19s_12ns_32_2_U6 : component DownResample_mul_19s_12ns_32_2
    generic map (
        ID => 6,
        NUM_STAGE => 2,
        din0_WIDTH => 19,
        din1_WIDTH => 12,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_746_p0,
        din1 => grp_fu_746_p1,
        ce => grp_fu_746_ce,
        dout => grp_fu_746_p2);

    DownResample_mul_19s_12ns_32_2_U7 : component DownResample_mul_19s_12ns_32_2
    generic map (
        ID => 7,
        NUM_STAGE => 2,
        din0_WIDTH => 19,
        din1_WIDTH => 12,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_778_p0,
        din1 => grp_fu_778_p1,
        ce => grp_fu_778_ce,
        dout => grp_fu_778_p2);

    DownResample_mul_19s_15s_34_2_U8 : component DownResample_mul_19s_15s_34_2
    generic map (
        ID => 8,
        NUM_STAGE => 2,
        din0_WIDTH => 19,
        din1_WIDTH => 15,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_852_p0,
        din1 => grp_fu_852_p1,
        ce => grp_fu_852_ce,
        dout => grp_fu_852_p2);

    DownResample_mul_19s_15s_34_2_U9 : component DownResample_mul_19s_15s_34_2
    generic map (
        ID => 9,
        NUM_STAGE => 2,
        din0_WIDTH => 19,
        din1_WIDTH => 15,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_884_p0,
        din1 => grp_fu_884_p1,
        ce => grp_fu_884_ce,
        dout => grp_fu_884_p2);

    DownResample_mul_18s_18s_34_3_U10 : component DownResample_mul_18s_18s_34_3
    generic map (
        ID => 10,
        NUM_STAGE => 3,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_906_p0,
        din1 => grp_fu_906_p1,
        ce => grp_fu_906_ce,
        dout => grp_fu_906_p2);

    DownResample_mul_18s_18s_34_3_U11 : component DownResample_mul_18s_18s_34_3
    generic map (
        ID => 11,
        NUM_STAGE => 3,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_915_p0,
        din1 => grp_fu_915_p1,
        ce => grp_fu_915_ce,
        dout => grp_fu_915_p2);

    DownResample_mul_19s_16ns_34_2_U12 : component DownResample_mul_19s_16ns_34_2
    generic map (
        ID => 12,
        NUM_STAGE => 2,
        din0_WIDTH => 19,
        din1_WIDTH => 16,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_963_p0,
        din1 => grp_fu_963_p1,
        ce => grp_fu_963_ce,
        dout => grp_fu_963_p2);

    DownResample_mul_19s_16ns_34_2_U13 : component DownResample_mul_19s_16ns_34_2
    generic map (
        ID => 13,
        NUM_STAGE => 2,
        din0_WIDTH => 19,
        din1_WIDTH => 16,
        dout_WIDTH => 34)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_995_p0,
        din1 => grp_fu_995_p1,
        ce => grp_fu_995_ce,
        dout => grp_fu_995_p2);





    -- the current state (ap_CS_fsm) of the state machine. --
    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_pp0_stg0_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it1 assign process. --
    ap_reg_ppiten_pp0_it1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it10 assign process. --
    ap_reg_ppiten_pp0_it10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it10 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
                    ap_reg_ppiten_pp0_it10 <= ap_reg_ppiten_pp0_it9;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it11 assign process. --
    ap_reg_ppiten_pp0_it11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it11 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
                    ap_reg_ppiten_pp0_it11 <= ap_reg_ppiten_pp0_it10;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it12 assign process. --
    ap_reg_ppiten_pp0_it12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it12 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
                    ap_reg_ppiten_pp0_it12 <= ap_reg_ppiten_pp0_it11;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it2 assign process. --
    ap_reg_ppiten_pp0_it2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
                    ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it3 assign process. --
    ap_reg_ppiten_pp0_it3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
                    ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it4 assign process. --
    ap_reg_ppiten_pp0_it4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
                    ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it5 assign process. --
    ap_reg_ppiten_pp0_it5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
                    ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it6 assign process. --
    ap_reg_ppiten_pp0_it6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
                    ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it7 assign process. --
    ap_reg_ppiten_pp0_it7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
                    ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it8 assign process. --
    ap_reg_ppiten_pp0_it8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it8 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
                    ap_reg_ppiten_pp0_it8 <= ap_reg_ppiten_pp0_it7;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it9 assign process. --
    ap_reg_ppiten_pp0_it9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it9 <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
                    ap_reg_ppiten_pp0_it9 <= ap_reg_ppiten_pp0_it8;
                end if; 
            end if;
        end if;
    end process;


    -- input_V_ap_vld_preg assign process. --
    input_V_ap_vld_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_V_ap_vld_preg <= ap_const_logic_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_const_logic_1) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
                    input_V_ap_vld_preg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = input_V_ap_vld)) then 
                    input_V_ap_vld_preg <= input_V_ap_vld;
                end if; 
            end if;
        end if;
    end process;


    -- input_V_preg assign process. --
    input_V_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                input_V_preg <= ap_const_lv36_0;
            else
                if ((ap_const_logic_1 = input_V_ap_vld)) then 
                    input_V_preg <= input_V;
                end if; 
            end if;
        end if;
    end process;


    -- phaseAcc_V assign process. --
    phaseAcc_V_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                phaseAcc_V <= ap_const_lv32_0;
            else
                if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_const_logic_1) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
                    phaseAcc_V <= p_Val2_7_fu_345_p2;
                end if; 
            end if;
        end if;
    end process;


    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then
                ap_reg_ppstg_p_Result_1_reg_1251_pp0_it1 <= p_Result_1_reg_1251;
                ap_reg_ppstg_p_Result_1_reg_1251_pp0_it2 <= ap_reg_ppstg_p_Result_1_reg_1251_pp0_it1;
                ap_reg_ppstg_p_Result_1_reg_1251_pp0_it3 <= ap_reg_ppstg_p_Result_1_reg_1251_pp0_it2;
                ap_reg_ppstg_p_Result_1_reg_1251_pp0_it4 <= ap_reg_ppstg_p_Result_1_reg_1251_pp0_it3;
                ap_reg_ppstg_p_Result_1_reg_1251_pp0_it5 <= ap_reg_ppstg_p_Result_1_reg_1251_pp0_it4;
                ap_reg_ppstg_p_Result_1_reg_1251_pp0_it6 <= ap_reg_ppstg_p_Result_1_reg_1251_pp0_it5;
                ap_reg_ppstg_p_Result_1_reg_1251_pp0_it7 <= ap_reg_ppstg_p_Result_1_reg_1251_pp0_it6;
                ap_reg_ppstg_reg_imag_V_11_load_reg_1334_pp0_it7 <= reg_imag_V_11_load_reg_1334;
                ap_reg_ppstg_reg_imag_V_11_load_reg_1334_pp0_it8 <= ap_reg_ppstg_reg_imag_V_11_load_reg_1334_pp0_it7;
                ap_reg_ppstg_reg_imag_V_13_load_reg_1324_pp0_it7 <= reg_imag_V_13_load_reg_1324;
                ap_reg_ppstg_reg_imag_V_3_load_reg_1374_pp0_it7 <= reg_imag_V_3_load_reg_1374;
                ap_reg_ppstg_reg_imag_V_5_load_reg_1364_pp0_it7 <= reg_imag_V_5_load_reg_1364;
                ap_reg_ppstg_reg_imag_V_5_load_reg_1364_pp0_it8 <= ap_reg_ppstg_reg_imag_V_5_load_reg_1364_pp0_it7;
                ap_reg_ppstg_reg_imag_V_7_load_reg_1354_pp0_it7 <= reg_imag_V_7_load_reg_1354;
                ap_reg_ppstg_reg_imag_V_7_load_reg_1354_pp0_it8 <= ap_reg_ppstg_reg_imag_V_7_load_reg_1354_pp0_it7;
                ap_reg_ppstg_reg_imag_V_7_load_reg_1354_pp0_it9 <= ap_reg_ppstg_reg_imag_V_7_load_reg_1354_pp0_it8;
                ap_reg_ppstg_reg_imag_V_9_load_reg_1344_pp0_it7 <= reg_imag_V_9_load_reg_1344;
                ap_reg_ppstg_reg_imag_V_9_load_reg_1344_pp0_it8 <= ap_reg_ppstg_reg_imag_V_9_load_reg_1344_pp0_it7;
                ap_reg_ppstg_reg_imag_V_9_load_reg_1344_pp0_it9 <= ap_reg_ppstg_reg_imag_V_9_load_reg_1344_pp0_it8;
                ap_reg_ppstg_reg_real_V_11_load_reg_1329_pp0_it7 <= reg_real_V_11_load_reg_1329;
                ap_reg_ppstg_reg_real_V_11_load_reg_1329_pp0_it8 <= ap_reg_ppstg_reg_real_V_11_load_reg_1329_pp0_it7;
                ap_reg_ppstg_reg_real_V_13_load_reg_1319_pp0_it7 <= reg_real_V_13_load_reg_1319;
                ap_reg_ppstg_reg_real_V_3_load_reg_1369_pp0_it7 <= reg_real_V_3_load_reg_1369;
                ap_reg_ppstg_reg_real_V_5_load_reg_1359_pp0_it7 <= reg_real_V_5_load_reg_1359;
                ap_reg_ppstg_reg_real_V_5_load_reg_1359_pp0_it8 <= ap_reg_ppstg_reg_real_V_5_load_reg_1359_pp0_it7;
                ap_reg_ppstg_reg_real_V_7_load_reg_1349_pp0_it7 <= reg_real_V_7_load_reg_1349;
                ap_reg_ppstg_reg_real_V_7_load_reg_1349_pp0_it8 <= ap_reg_ppstg_reg_real_V_7_load_reg_1349_pp0_it7;
                ap_reg_ppstg_reg_real_V_7_load_reg_1349_pp0_it9 <= ap_reg_ppstg_reg_real_V_7_load_reg_1349_pp0_it8;
                ap_reg_ppstg_reg_real_V_9_load_reg_1339_pp0_it7 <= reg_real_V_9_load_reg_1339;
                ap_reg_ppstg_reg_real_V_9_load_reg_1339_pp0_it8 <= ap_reg_ppstg_reg_real_V_9_load_reg_1339_pp0_it7;
                ap_reg_ppstg_reg_real_V_9_load_reg_1339_pp0_it9 <= ap_reg_ppstg_reg_real_V_9_load_reg_1339_pp0_it8;
                ap_reg_ppstg_tmp_2_reg_1246_pp0_it1 <= tmp_2_reg_1246;
                ap_reg_ppstg_tmp_2_reg_1246_pp0_it2 <= ap_reg_ppstg_tmp_2_reg_1246_pp0_it1;
                ap_reg_ppstg_tmp_4_reg_1256_pp0_it1 <= tmp_4_reg_1256;
                ap_reg_ppstg_tmp_4_reg_1256_pp0_it2 <= ap_reg_ppstg_tmp_4_reg_1256_pp0_it1;
                ap_reg_ppstg_tmp_4_reg_1256_pp0_it3 <= ap_reg_ppstg_tmp_4_reg_1256_pp0_it2;
                ap_reg_ppstg_tmp_4_reg_1256_pp0_it4 <= ap_reg_ppstg_tmp_4_reg_1256_pp0_it3;
                ap_reg_ppstg_tmp_4_reg_1256_pp0_it5 <= ap_reg_ppstg_tmp_4_reg_1256_pp0_it4;
                ap_reg_ppstg_tmp_4_reg_1256_pp0_it6 <= ap_reg_ppstg_tmp_4_reg_1256_pp0_it5;
                ap_reg_ppstg_tmp_4_reg_1256_pp0_it7 <= ap_reg_ppstg_tmp_4_reg_1256_pp0_it6;
                ap_reg_ppstg_tmp_4_reg_1256_pp0_it8 <= ap_reg_ppstg_tmp_4_reg_1256_pp0_it7;
                ap_reg_ppstg_tmp_4_reg_1256_pp0_it9 <= ap_reg_ppstg_tmp_4_reg_1256_pp0_it8;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it9) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then
                cosT_V_load_1_reg_1449 <= cosT_V_q1;
                sinT_V_load_1_reg_1454 <= sinT_V_q1;
                tmp_21_reg_1464 <= p_Val2_26_0_2_fu_809_p2(33 downto 16);
                tmp_22_reg_1474 <= p_Val2_31_0_2_fu_830_p2(33 downto 16);
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then
                cosT_V_load_reg_1271 <= cosT_V_q0;
                sinT_V_load_reg_1276 <= sinT_V_q0;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_const_logic_1) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then
                p_Result_1_reg_1251 <= p_Val2_6_1_fu_299_p2(31 downto 22);
                p_Result_s_reg_1241 <= p_Val2_6_fu_287_p2(31 downto 22);
                tmp_2_reg_1246 <= tmp_2_fu_315_p1;
                tmp_4_reg_1256 <= input_V_in_sig(35 downto 18);
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then
                p_Val2_9_reg_1399 <= grp_fu_598_p2;
                p_Val2_s_reg_1404 <= grp_fu_621_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it12) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then
                reg_imag_V_0 <= grp_fu_915_p2(33 downto 16);
                reg_imag_V_2 <= reg_imag_V_0;
                reg_imag_V_4 <= reg_imag_V_2;
                reg_imag_V_6 <= reg_imag_V_4;
                reg_imag_V_8 <= reg_imag_V_6;
                reg_real_V_0 <= grp_fu_906_p2(33 downto 16);
                reg_real_V_2 <= reg_real_V_0;
                reg_real_V_4 <= reg_real_V_2;
                reg_real_V_6 <= reg_real_V_4;
                reg_real_V_8 <= reg_real_V_6;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it6) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then
                reg_imag_V_1 <= tmp_9_reg_1303;
                reg_imag_V_11 <= reg_imag_V_9;
                reg_imag_V_11_load_reg_1334 <= reg_imag_V_11;
                reg_imag_V_13 <= reg_imag_V_11;
                reg_imag_V_13_load_reg_1324 <= reg_imag_V_13;
                reg_imag_V_15 <= reg_imag_V_13;
                reg_imag_V_15_load_reg_1314 <= reg_imag_V_15;
                reg_imag_V_17 <= reg_imag_V_15;
                reg_imag_V_1_load_reg_1384 <= reg_imag_V_1;
                reg_imag_V_3 <= reg_imag_V_1;
                reg_imag_V_3_load_reg_1374 <= reg_imag_V_3;
                reg_imag_V_5 <= reg_imag_V_3;
                reg_imag_V_5_load_reg_1364 <= reg_imag_V_5;
                reg_imag_V_7 <= reg_imag_V_5;
                reg_imag_V_7_load_reg_1354 <= reg_imag_V_7;
                reg_imag_V_9 <= reg_imag_V_7;
                reg_imag_V_9_load_reg_1344 <= reg_imag_V_9;
                reg_real_V_1 <= tmp_7_reg_1297;
                reg_real_V_11 <= reg_real_V_9;
                reg_real_V_11_load_reg_1329 <= reg_real_V_11;
                reg_real_V_13 <= reg_real_V_11;
                reg_real_V_13_load_reg_1319 <= reg_real_V_13;
                reg_real_V_15 <= reg_real_V_13;
                reg_real_V_15_load_reg_1309 <= reg_real_V_15;
                reg_real_V_17 <= reg_real_V_15;
                reg_real_V_1_load_reg_1379 <= reg_real_V_1;
                reg_real_V_3 <= reg_real_V_1;
                reg_real_V_3_load_reg_1369 <= reg_real_V_3;
                reg_real_V_5 <= reg_real_V_3;
                reg_real_V_5_load_reg_1359 <= reg_real_V_5;
                reg_real_V_7 <= reg_real_V_5;
                reg_real_V_7_load_reg_1349 <= reg_real_V_7;
                reg_real_V_9 <= reg_real_V_7;
                reg_real_V_9_load_reg_1339 <= reg_real_V_9;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then
                tmp_17_reg_1434 <= p_Val2_26_0_1_fu_706_p2(29 downto 16);
                tmp_20_reg_1444 <= p_Val2_31_0_1_fu_724_p2(29 downto 16);
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it10) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then
                tmp_23_reg_1500 <= p_Val2_26_0_3_fu_928_p2(33 downto 16);
                tmp_24_reg_1510 <= p_Val2_31_0_3_fu_941_p2(33 downto 16);
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it11) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then
                tmp_25_reg_1515 <= p_Val2_26_0_4_fu_1018_p2(33 downto 16);
                tmp_26_reg_1520 <= p_Val2_31_0_4_fu_1031_p2(33 downto 16);
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then
                tmp_7_reg_1297 <= grp_fu_368_p2(33 downto 16);
                tmp_9_reg_1303 <= grp_fu_377_p2(33 downto 16);
            end if;
        end if;
    end process;

    -- the next state (ap_NS_fsm) of the state machine. --
    ap_NS_fsm_assign_proc : process (input_V_ap_vld_in_sig, ap_CS_fsm, ap_sig_pprstidle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_pp0_stg0_fsm_0 => 
                ap_NS_fsm <= ap_ST_pp0_stg0_fsm_0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    
    tmp_fu_265_p3_temp <= signed(tmp_fu_265_p3);
    FreqOffsetTmp_V_fu_273_p1 <= std_logic_vector(resize(tmp_fu_265_p3_temp,32));

    
    ap_reg_ppstg_tmp_4_reg_1256_pp0_it9_temp <= signed(ap_reg_ppstg_tmp_4_reg_1256_pp0_it9);
    OP1_V_cast_27_fu_900_p1 <= std_logic_vector(resize(ap_reg_ppstg_tmp_4_reg_1256_pp0_it9_temp,34));

    
    ap_reg_ppstg_tmp_2_reg_1246_pp0_it2_temp <= signed(ap_reg_ppstg_tmp_2_reg_1246_pp0_it2);
    OP1_V_cast_fu_362_p1 <= std_logic_vector(resize(ap_reg_ppstg_tmp_2_reg_1246_pp0_it2_temp,34));

    ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
    ap_sig_pprstidle_pp0 <= ap_const_logic_0;
    cosT_V_address0 <= tmp_5_fu_357_p1(10 - 1 downto 0);
    cosT_V_address1 <= tmp_15_1_fu_671_p1(10 - 1 downto 0);

    -- cosT_V_ce0 assign process. --
    cosT_V_ce0_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm, ap_reg_ppiten_pp0_it1)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            cosT_V_ce0 <= ap_const_logic_1;
        else 
            cosT_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    -- cosT_V_ce1 assign process. --
    cosT_V_ce1_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm, ap_reg_ppiten_pp0_it8)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            cosT_V_ce1 <= ap_const_logic_1;
        else 
            cosT_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    -- grp_fu_368_ce assign process. --
    grp_fu_368_ce_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            grp_fu_368_ce <= ap_const_logic_1;
        else 
            grp_fu_368_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_368_p0 <= cosT_V_load_reg_1271;
    grp_fu_368_p1 <= OP1_V_cast_fu_362_p1(18 - 1 downto 0);

    -- grp_fu_377_ce assign process. --
    grp_fu_377_ce_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            grp_fu_377_ce <= ap_const_logic_1;
        else 
            grp_fu_377_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_377_p0 <= sinT_V_load_reg_1276;
    grp_fu_377_p1 <= OP1_V_cast_fu_362_p1(18 - 1 downto 0);

    -- grp_fu_598_ce assign process. --
    grp_fu_598_ce_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            grp_fu_598_ce <= ap_const_logic_1;
        else 
            grp_fu_598_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_598_p0 <= r_V_fu_588_p2;
    grp_fu_598_p1 <= ap_const_lv27_93(8 - 1 downto 0);

    -- grp_fu_621_ce assign process. --
    grp_fu_621_ce_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            grp_fu_621_ce <= ap_const_logic_1;
        else 
            grp_fu_621_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_621_p0 <= r_V_1_fu_611_p2;
    grp_fu_621_p1 <= ap_const_lv27_93(8 - 1 downto 0);

    -- grp_fu_643_ce assign process. --
    grp_fu_643_ce_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            grp_fu_643_ce <= ap_const_logic_1;
        else 
            grp_fu_643_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_643_p0 <= r_V_0_1_fu_633_p2;
    grp_fu_643_p1 <= ap_const_lv30_3FFFFC5B(11 - 1 downto 0);

    -- grp_fu_665_ce assign process. --
    grp_fu_665_ce_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            grp_fu_665_ce <= ap_const_logic_1;
        else 
            grp_fu_665_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_665_p0 <= r_V_1_0_1_fu_655_p2;
    grp_fu_665_p1 <= ap_const_lv30_3FFFFC5B(11 - 1 downto 0);

    -- grp_fu_746_ce assign process. --
    grp_fu_746_ce_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            grp_fu_746_ce <= ap_const_logic_1;
        else 
            grp_fu_746_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_746_p0 <= r_V_0_2_fu_736_p2;
    grp_fu_746_p1 <= ap_const_lv32_D69(12 - 1 downto 0);

    -- grp_fu_778_ce assign process. --
    grp_fu_778_ce_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            grp_fu_778_ce <= ap_const_logic_1;
        else 
            grp_fu_778_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_778_p0 <= r_V_1_0_2_fu_768_p2;
    grp_fu_778_p1 <= ap_const_lv32_D69(12 - 1 downto 0);

    -- grp_fu_852_ce assign process. --
    grp_fu_852_ce_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            grp_fu_852_ce <= ap_const_logic_1;
        else 
            grp_fu_852_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_852_p0 <= r_V_0_3_fu_842_p2;
    grp_fu_852_p1 <= ap_const_lv34_3FFFFD816(15 - 1 downto 0);

    -- grp_fu_884_ce assign process. --
    grp_fu_884_ce_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            grp_fu_884_ce <= ap_const_logic_1;
        else 
            grp_fu_884_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_884_p0 <= r_V_1_0_3_fu_874_p2;
    grp_fu_884_p1 <= ap_const_lv34_3FFFFD816(15 - 1 downto 0);

    -- grp_fu_906_ce assign process. --
    grp_fu_906_ce_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            grp_fu_906_ce <= ap_const_logic_1;
        else 
            grp_fu_906_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_906_p0 <= cosT_V_load_1_reg_1449;
    grp_fu_906_p1 <= OP1_V_cast_27_fu_900_p1(18 - 1 downto 0);

    -- grp_fu_915_ce assign process. --
    grp_fu_915_ce_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            grp_fu_915_ce <= ap_const_logic_1;
        else 
            grp_fu_915_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_915_p0 <= sinT_V_load_1_reg_1454;
    grp_fu_915_p1 <= OP1_V_cast_27_fu_900_p1(18 - 1 downto 0);

    -- grp_fu_963_ce assign process. --
    grp_fu_963_ce_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            grp_fu_963_ce <= ap_const_logic_1;
        else 
            grp_fu_963_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_963_p0 <= r_V_0_4_fu_953_p2;
    grp_fu_963_p1 <= ap_const_lv34_9D93(16 - 1 downto 0);

    -- grp_fu_995_ce assign process. --
    grp_fu_995_ce_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            grp_fu_995_ce <= ap_const_logic_1;
        else 
            grp_fu_995_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_995_p0 <= r_V_1_0_4_fu_985_p2;
    grp_fu_995_p1 <= ap_const_lv34_9D93(16 - 1 downto 0);

    -- input_V_ap_vld_in_sig assign process. --
    input_V_ap_vld_in_sig_assign_proc : process(input_V_ap_vld, input_V_ap_vld_preg)
    begin
        if ((ap_const_logic_1 = input_V_ap_vld)) then 
            input_V_ap_vld_in_sig <= input_V_ap_vld;
        else 
            input_V_ap_vld_in_sig <= input_V_ap_vld_preg;
        end if; 
    end process;


    -- input_V_in_sig assign process. --
    input_V_in_sig_assign_proc : process(input_V, input_V_preg, input_V_ap_vld)
    begin
        if ((ap_const_logic_1 = input_V_ap_vld)) then 
            input_V_in_sig <= input_V;
        else 
            input_V_in_sig <= input_V_preg;
        end if; 
    end process;

    output_imag_V_address0 <= ap_const_lv64_0(1 - 1 downto 0);

    -- output_imag_V_ce0 assign process. --
    output_imag_V_ce0_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm, ap_reg_ppiten_pp0_it12)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it12) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            output_imag_V_ce0 <= ap_const_logic_1;
        else 
            output_imag_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_imag_V_d0 <= p_Val2_12_fu_1224_p2(33 downto 16);

    -- output_imag_V_we0 assign process. --
    output_imag_V_we0_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm, ap_reg_ppiten_pp0_it12)
    begin
        if ((((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it12) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0)))))) then 
            output_imag_V_we0 <= ap_const_logic_1;
        else 
            output_imag_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_real_V_address0 <= ap_const_lv64_0(1 - 1 downto 0);

    -- output_real_V_ce0 assign process. --
    output_real_V_ce0_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm, ap_reg_ppiten_pp0_it12)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it12) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            output_real_V_ce0 <= ap_const_logic_1;
        else 
            output_real_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_real_V_d0 <= p_Val2_10_fu_1192_p2(33 downto 16);

    -- output_real_V_we0 assign process. --
    output_real_V_we0_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm, ap_reg_ppiten_pp0_it12)
    begin
        if ((((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it12) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0)))))) then 
            output_real_V_we0 <= ap_const_logic_1;
        else 
            output_real_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_Val2_10_fu_1192_p2 <= std_logic_vector(unsigned(tmp_11_fu_1185_p3) + unsigned(p_Val2_8_fu_1177_p3));
    p_Val2_11_fu_1209_p3 <= (reg_imag_V_8 & ap_const_lv16_0);
    p_Val2_12_fu_1224_p2 <= std_logic_vector(unsigned(tmp_16_fu_1217_p3) + unsigned(p_Val2_11_fu_1209_p3));
    
    tmp_13_fu_694_p3_temp <= signed(tmp_13_fu_694_p3);
    p_Val2_26_0_1_fu_706_p0 <= std_logic_vector(resize(tmp_13_fu_694_p3_temp,30));

    p_Val2_26_0_1_fu_706_p2 <= std_logic_vector(unsigned(p_Val2_26_0_1_fu_706_p0) + unsigned(grp_fu_643_p2));
    
    tmp_18_fu_794_p3_temp <= signed(tmp_18_fu_794_p3);
    p_Val2_26_0_2_fu_809_p0 <= std_logic_vector(resize(tmp_18_fu_794_p3_temp,34));

    
    grp_fu_746_p2_temp <= signed(grp_fu_746_p2);
    p_Val2_26_0_2_fu_809_p1 <= std_logic_vector(resize(grp_fu_746_p2_temp,34));

    p_Val2_26_0_2_fu_809_p2 <= std_logic_vector(unsigned(p_Val2_26_0_2_fu_809_p0) + unsigned(p_Val2_26_0_2_fu_809_p1));
    p_Val2_26_0_3_fu_928_p2 <= std_logic_vector(unsigned(tmp_60_0_3_fu_921_p3) + unsigned(grp_fu_852_p2));
    p_Val2_26_0_4_fu_1018_p2 <= std_logic_vector(unsigned(tmp_60_0_4_fu_1011_p3) + unsigned(grp_fu_963_p2));
    
    tmp_15_fu_712_p3_temp <= signed(tmp_15_fu_712_p3);
    p_Val2_31_0_1_fu_724_p0 <= std_logic_vector(resize(tmp_15_fu_712_p3_temp,30));

    p_Val2_31_0_1_fu_724_p2 <= std_logic_vector(unsigned(p_Val2_31_0_1_fu_724_p0) + unsigned(grp_fu_665_p2));
    
    tmp_27_fu_815_p3_temp <= signed(tmp_27_fu_815_p3);
    p_Val2_31_0_2_fu_830_p0 <= std_logic_vector(resize(tmp_27_fu_815_p3_temp,34));

    
    grp_fu_778_p2_temp <= signed(grp_fu_778_p2);
    p_Val2_31_0_2_fu_830_p1 <= std_logic_vector(resize(grp_fu_778_p2_temp,34));

    p_Val2_31_0_2_fu_830_p2 <= std_logic_vector(unsigned(p_Val2_31_0_2_fu_830_p0) + unsigned(p_Val2_31_0_2_fu_830_p1));
    p_Val2_31_0_3_fu_941_p2 <= std_logic_vector(unsigned(tmp_67_0_3_fu_934_p3) + unsigned(grp_fu_884_p2));
    p_Val2_31_0_4_fu_1031_p2 <= std_logic_vector(unsigned(tmp_67_0_4_fu_1024_p3) + unsigned(grp_fu_995_p2));
    p_Val2_3_1_fu_293_p0 <= FreqOffsetTmp_V_fu_273_p1;
    p_Val2_3_1_fu_293_p2 <= std_logic_vector(unsigned(p_Val2_3_1_fu_293_p0) + unsigned(DDC_freq_norm_1_V));
    p_Val2_4_fu_339_p2 <= std_logic_vector(shift_left(unsigned(p_Val2_3_1_fu_293_p2),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    p_Val2_6_1_fu_299_p2 <= std_logic_vector(unsigned(p_Val2_3_1_fu_293_p2) + unsigned(phaseAcc_V));
    p_Val2_6_fu_287_p1 <= FreqOffsetTmp_V_fu_273_p1;
    p_Val2_6_fu_287_p2 <= std_logic_vector(unsigned(tmp1_fu_281_p2) + unsigned(p_Val2_6_fu_287_p1));
    p_Val2_7_fu_345_p2 <= std_logic_vector(unsigned(p_Val2_4_fu_339_p2) + unsigned(phaseAcc_V));
    p_Val2_8_fu_1177_p3 <= (reg_real_V_8 & ap_const_lv16_0);
    
    reg_real_V_15_load_reg_1309_temp <= signed(reg_real_V_15_load_reg_1309);
    r_V_0_1_fu_633_p0 <= std_logic_vector(resize(reg_real_V_15_load_reg_1309_temp,19));

    
    reg_real_V_1_load_reg_1379_temp <= signed(reg_real_V_1_load_reg_1379);
    r_V_0_1_fu_633_p1 <= std_logic_vector(resize(reg_real_V_1_load_reg_1379_temp,19));

    r_V_0_1_fu_633_p2 <= std_logic_vector(unsigned(r_V_0_1_fu_633_p0) + unsigned(r_V_0_1_fu_633_p1));
    
    ap_reg_ppstg_reg_real_V_13_load_reg_1319_pp0_it7_temp <= signed(ap_reg_ppstg_reg_real_V_13_load_reg_1319_pp0_it7);
    r_V_0_2_fu_736_p0 <= std_logic_vector(resize(ap_reg_ppstg_reg_real_V_13_load_reg_1319_pp0_it7_temp,19));

    
    ap_reg_ppstg_reg_real_V_3_load_reg_1369_pp0_it7_temp <= signed(ap_reg_ppstg_reg_real_V_3_load_reg_1369_pp0_it7);
    r_V_0_2_fu_736_p1 <= std_logic_vector(resize(ap_reg_ppstg_reg_real_V_3_load_reg_1369_pp0_it7_temp,19));

    r_V_0_2_fu_736_p2 <= std_logic_vector(unsigned(r_V_0_2_fu_736_p0) + unsigned(r_V_0_2_fu_736_p1));
    
    ap_reg_ppstg_reg_real_V_11_load_reg_1329_pp0_it8_temp <= signed(ap_reg_ppstg_reg_real_V_11_load_reg_1329_pp0_it8);
    r_V_0_3_fu_842_p0 <= std_logic_vector(resize(ap_reg_ppstg_reg_real_V_11_load_reg_1329_pp0_it8_temp,19));

    
    ap_reg_ppstg_reg_real_V_5_load_reg_1359_pp0_it8_temp <= signed(ap_reg_ppstg_reg_real_V_5_load_reg_1359_pp0_it8);
    r_V_0_3_fu_842_p1 <= std_logic_vector(resize(ap_reg_ppstg_reg_real_V_5_load_reg_1359_pp0_it8_temp,19));

    r_V_0_3_fu_842_p2 <= std_logic_vector(unsigned(r_V_0_3_fu_842_p0) + unsigned(r_V_0_3_fu_842_p1));
    
    ap_reg_ppstg_reg_real_V_9_load_reg_1339_pp0_it9_temp <= signed(ap_reg_ppstg_reg_real_V_9_load_reg_1339_pp0_it9);
    r_V_0_4_fu_953_p0 <= std_logic_vector(resize(ap_reg_ppstg_reg_real_V_9_load_reg_1339_pp0_it9_temp,19));

    
    ap_reg_ppstg_reg_real_V_7_load_reg_1349_pp0_it9_temp <= signed(ap_reg_ppstg_reg_real_V_7_load_reg_1349_pp0_it9);
    r_V_0_4_fu_953_p1 <= std_logic_vector(resize(ap_reg_ppstg_reg_real_V_7_load_reg_1349_pp0_it9_temp,19));

    r_V_0_4_fu_953_p2 <= std_logic_vector(unsigned(r_V_0_4_fu_953_p0) + unsigned(r_V_0_4_fu_953_p1));
    
    reg_imag_V_15_load_reg_1314_temp <= signed(reg_imag_V_15_load_reg_1314);
    r_V_1_0_1_fu_655_p0 <= std_logic_vector(resize(reg_imag_V_15_load_reg_1314_temp,19));

    
    reg_imag_V_1_load_reg_1384_temp <= signed(reg_imag_V_1_load_reg_1384);
    r_V_1_0_1_fu_655_p1 <= std_logic_vector(resize(reg_imag_V_1_load_reg_1384_temp,19));

    r_V_1_0_1_fu_655_p2 <= std_logic_vector(unsigned(r_V_1_0_1_fu_655_p0) + unsigned(r_V_1_0_1_fu_655_p1));
    
    ap_reg_ppstg_reg_imag_V_13_load_reg_1324_pp0_it7_temp <= signed(ap_reg_ppstg_reg_imag_V_13_load_reg_1324_pp0_it7);
    r_V_1_0_2_fu_768_p0 <= std_logic_vector(resize(ap_reg_ppstg_reg_imag_V_13_load_reg_1324_pp0_it7_temp,19));

    
    ap_reg_ppstg_reg_imag_V_3_load_reg_1374_pp0_it7_temp <= signed(ap_reg_ppstg_reg_imag_V_3_load_reg_1374_pp0_it7);
    r_V_1_0_2_fu_768_p1 <= std_logic_vector(resize(ap_reg_ppstg_reg_imag_V_3_load_reg_1374_pp0_it7_temp,19));

    r_V_1_0_2_fu_768_p2 <= std_logic_vector(unsigned(r_V_1_0_2_fu_768_p0) + unsigned(r_V_1_0_2_fu_768_p1));
    
    ap_reg_ppstg_reg_imag_V_11_load_reg_1334_pp0_it8_temp <= signed(ap_reg_ppstg_reg_imag_V_11_load_reg_1334_pp0_it8);
    r_V_1_0_3_fu_874_p0 <= std_logic_vector(resize(ap_reg_ppstg_reg_imag_V_11_load_reg_1334_pp0_it8_temp,19));

    
    ap_reg_ppstg_reg_imag_V_5_load_reg_1364_pp0_it8_temp <= signed(ap_reg_ppstg_reg_imag_V_5_load_reg_1364_pp0_it8);
    r_V_1_0_3_fu_874_p1 <= std_logic_vector(resize(ap_reg_ppstg_reg_imag_V_5_load_reg_1364_pp0_it8_temp,19));

    r_V_1_0_3_fu_874_p2 <= std_logic_vector(unsigned(r_V_1_0_3_fu_874_p0) + unsigned(r_V_1_0_3_fu_874_p1));
    
    ap_reg_ppstg_reg_imag_V_9_load_reg_1344_pp0_it9_temp <= signed(ap_reg_ppstg_reg_imag_V_9_load_reg_1344_pp0_it9);
    r_V_1_0_4_fu_985_p0 <= std_logic_vector(resize(ap_reg_ppstg_reg_imag_V_9_load_reg_1344_pp0_it9_temp,19));

    
    ap_reg_ppstg_reg_imag_V_7_load_reg_1354_pp0_it9_temp <= signed(ap_reg_ppstg_reg_imag_V_7_load_reg_1354_pp0_it9);
    r_V_1_0_4_fu_985_p1 <= std_logic_vector(resize(ap_reg_ppstg_reg_imag_V_7_load_reg_1354_pp0_it9_temp,19));

    r_V_1_0_4_fu_985_p2 <= std_logic_vector(unsigned(r_V_1_0_4_fu_985_p0) + unsigned(r_V_1_0_4_fu_985_p1));
    
    reg_imag_V_17_temp <= signed(reg_imag_V_17);
    r_V_1_fu_611_p0 <= std_logic_vector(resize(reg_imag_V_17_temp,19));

    
    tmp_9_reg_1303_temp <= signed(tmp_9_reg_1303);
    r_V_1_fu_611_p1 <= std_logic_vector(resize(tmp_9_reg_1303_temp,19));

    r_V_1_fu_611_p2 <= std_logic_vector(unsigned(r_V_1_fu_611_p0) + unsigned(r_V_1_fu_611_p1));
    
    reg_real_V_17_temp <= signed(reg_real_V_17);
    r_V_fu_588_p0 <= std_logic_vector(resize(reg_real_V_17_temp,19));

    
    tmp_7_reg_1297_temp <= signed(tmp_7_reg_1297);
    r_V_fu_588_p1 <= std_logic_vector(resize(tmp_7_reg_1297_temp,19));

    r_V_fu_588_p2 <= std_logic_vector(unsigned(r_V_fu_588_p0) + unsigned(r_V_fu_588_p1));
    sinT_V_address0 <= tmp_5_fu_357_p1(10 - 1 downto 0);
    sinT_V_address1 <= tmp_15_1_fu_671_p1(10 - 1 downto 0);

    -- sinT_V_ce0 assign process. --
    sinT_V_ce0_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm, ap_reg_ppiten_pp0_it1)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            sinT_V_ce0 <= ap_const_logic_1;
        else 
            sinT_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    -- sinT_V_ce1 assign process. --
    sinT_V_ce1_assign_proc : process(input_V_ap_vld_in_sig, ap_CS_fsm, ap_reg_ppiten_pp0_it8)
    begin
        if (((ap_ST_pp0_stg0_fsm_0 = ap_CS_fsm) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and not(((ap_const_logic_1 = ap_const_logic_1) and (input_V_ap_vld_in_sig = ap_const_logic_0))))) then 
            sinT_V_ce1 <= ap_const_logic_1;
        else 
            sinT_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    tmp1_fu_281_p2 <= std_logic_vector(unsigned(DDC_freq_norm_0_V) + unsigned(phaseAcc_V));
    tmp_11_fu_1185_p3 <= (tmp_25_reg_1515 & ap_const_lv16_0);
    tmp_12_fu_685_p4 <= p_Val2_s_reg_1404(26 downto 16);
    tmp_13_fu_694_p3 <= (tmp_8_fu_676_p4 & ap_const_lv16_0);
    tmp_15_1_fu_671_p1 <= std_logic_vector(resize(unsigned(ap_reg_ppstg_p_Result_1_reg_1251_pp0_it7),64));
    tmp_15_fu_712_p3 <= (tmp_12_fu_685_p4 & ap_const_lv16_0);
    tmp_16_fu_1217_p3 <= (tmp_26_reg_1520 & ap_const_lv16_0);
    tmp_18_fu_794_p3 <= (tmp_17_reg_1434 & ap_const_lv16_0);
    tmp_1_fu_255_p4 <= FreqOffsetIn_V(24 downto 8);
    tmp_27_fu_815_p3 <= (tmp_20_reg_1444 & ap_const_lv16_0);
    tmp_2_fu_315_p1 <= input_V_in_sig(18 - 1 downto 0);
    tmp_5_fu_357_p1 <= std_logic_vector(resize(unsigned(p_Result_s_reg_1241),64));
    tmp_60_0_3_fu_921_p3 <= (tmp_21_reg_1464 & ap_const_lv16_0);
    tmp_60_0_4_fu_1011_p3 <= (tmp_23_reg_1500 & ap_const_lv16_0);
    tmp_67_0_3_fu_934_p3 <= (tmp_22_reg_1474 & ap_const_lv16_0);
    tmp_67_0_4_fu_1024_p3 <= (tmp_24_reg_1510 & ap_const_lv16_0);
    tmp_8_fu_676_p4 <= p_Val2_9_reg_1399(26 downto 16);
    tmp_fu_265_p3 <= (tmp_1_fu_255_p4 & ap_const_lv8_0);
end behav;
