-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2014.2
-- Copyright (C) 2014 Xilinx Inc. All rights reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity demod_mux_Data_SCIndex_with_Gamma_80MHz_V_rom is 
    generic(
             dwidth     : integer := 2; 
             awidth     : integer := 9; 
             mem_size    : integer := 512
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of demod_mux_Data_SCIndex_with_Gamma_80MHz_V_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 to 1=> "00", 2 to 10=> "11", 11 => "00", 12 to 38=> "11", 39 => "00", 40 to 74=> "11", 
    75 => "00", 76 to 102=> "11", 103 => "00", 104 to 122=> "11", 123 to 389=> "00", 390 to 408=> "01", 
    409 => "00", 410 to 436=> "01", 437 => "00", 438 to 447=> "01", 448 to 472=> "11", 473 => "00", 
    474 to 500=> "11", 501 => "00", 502 to 510=> "11", 511 => "00" );


attribute EQUIVALENT_REGISTER_REMOVAL : string;
begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity demod_mux_Data_SCIndex_with_Gamma_80MHz_V is
    generic (
        DataWidth : INTEGER := 2;
        AddressRange : INTEGER := 512;
        AddressWidth : INTEGER := 9);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of demod_mux_Data_SCIndex_with_Gamma_80MHz_V is
    component demod_mux_Data_SCIndex_with_Gamma_80MHz_V_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;




begin
    demod_mux_Data_SCIndex_with_Gamma_80MHz_V_rom_U :  component demod_mux_Data_SCIndex_with_Gamma_80MHz_V_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


