include ( Intel_MKL.cmake )

macro( SVU_ADD_MODELBUILDER_LIBRARY_FOR_BEL )
	SET(ARGLIST ${ARGN})
	LIST(GET ARGLIST 0 _TARGET_NAME )

	SVU_ADD_MODELBUILDER_LIBRARY( ${ARGLIST} )

	set_property( TARGET ${_TARGET_NAME} APPEND PROPERTY COMPILE_DEFINITIONS MODELBUILDER_BUILD )

	# Install the SystemVue model library
	install( 
		TARGETS ${_TARGET_NAME}
		RUNTIME	DESTINATION ${SVU_ARCH}/Autoload CONFIGURATIONS Release
	)

	set_target_properties( ${_TARGET_NAME} PROPERTIES
		COMPILE_FLAGS -I"${MKL_INSTALL_DIR}/include"
	)

	SVU_LINK_MKL_COMMERCIAL( ${_TARGET_NAME} )
endmacro( SVU_ADD_MODELBUILDER_LIBRARY_FOR_BEL )