// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2010a.198 Production Release
//  HLS Date:       Tue Nov  2 16:03:18 PST 2010
// 
//  Generated by:   junakhan@PTOLEMYJK64
//  Generated date: Wed Mar 02 14:30:56 2011
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    Mapper
//  Generated from file(s):
//    2) $PROJECT_HOME/source/mapper.cpp
// ------------------------------------------------------------------


module MapperVerilog (
  dataIn, realOut, imagOut
);
  input [5:0] dataIn;
  output [3:0] realOut;
  output [3:0] imagOut;


  wire[0:0] std_Complex_base_int_std_Complex_value_int_imag_mux_nl;
  wire[0:0] std_Complex_base_int_std_Complex_value_int_imag_mux_1_nl;
  wire[0:0] std_Complex_base_int_std_Complex_value_int_imag_mux_2_nl;
  wire[0:0] std_Complex_base_int_std_Complex_value_int_real_mux_nl;
  wire[0:0] std_Complex_base_int_std_Complex_value_int_real_mux_1_nl;
  wire[0:0] std_Complex_base_int_std_Complex_value_int_real_mux_2_nl;
  assign std_Complex_base_int_std_Complex_value_int_imag_mux_nl = MUX_s_1_64_1({1'b0
      , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0
      , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0
      , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b1 , 1'b1
      , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1
      , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1
      , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1}, dataIn);
  assign std_Complex_base_int_std_Complex_value_int_imag_mux_1_nl = MUX_s_1_64_1({1'b0
      , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b1 , 1'b1 , 1'b1 , 1'b1
      , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0
      , 1'b0 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1
      , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0
      , 1'b0 , 1'b0 , 1'b0 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1
      , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0}, dataIn);
  assign std_Complex_base_int_std_Complex_value_int_imag_mux_2_nl = MUX_s_1_64_1({1'b0
      , 1'b0 , 1'b1 , 1'b1 , 1'b0 , 1'b0 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b0 , 1'b0
      , 1'b1 , 1'b1 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b1 , 1'b1 , 1'b0 , 1'b0 , 1'b1
      , 1'b1 , 1'b1 , 1'b1 , 1'b0 , 1'b0 , 1'b1 , 1'b1 , 1'b0 , 1'b0 , 1'b1 , 1'b1
      , 1'b0 , 1'b0 , 1'b1 , 1'b1 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b1 , 1'b1 , 1'b0
      , 1'b0 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b0 , 1'b0 , 1'b1 , 1'b1 , 1'b0 , 1'b0
      , 1'b0 , 1'b0 , 1'b1 , 1'b1 , 1'b0 , 1'b0 , 1'b1 , 1'b1}, dataIn);
  assign imagOut = {(std_Complex_base_int_std_Complex_value_int_imag_mux_nl) , (std_Complex_base_int_std_Complex_value_int_imag_mux_1_nl)
      , (std_Complex_base_int_std_Complex_value_int_imag_mux_2_nl) , 1'b1};
  assign std_Complex_base_int_std_Complex_value_int_real_mux_nl = MUX_s_1_64_1({1'b0
      , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0
      , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1
      , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b0 , 1'b0
      , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0
      , 1'b0 , 1'b0 , 1'b0 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1
      , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1}, dataIn);
  assign std_Complex_base_int_std_Complex_value_int_real_mux_1_nl = MUX_s_1_64_1({1'b0
      , 1'b0 , 1'b0 , 1'b0 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b0 , 1'b0 , 1'b0 , 1'b0
      , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b0 , 1'b0 , 1'b0
      , 1'b0 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b0
      , 1'b0 , 1'b0 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b0 , 1'b0 , 1'b0 , 1'b0 , 1'b1
      , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b0 , 1'b0 , 1'b0 , 1'b0
      , 1'b1 , 1'b1 , 1'b1 , 1'b1 , 1'b0 , 1'b0 , 1'b0 , 1'b0}, dataIn);
  assign std_Complex_base_int_std_Complex_value_int_real_mux_2_nl = MUX_s_1_64_1({1'b0
      , 1'b1 , 1'b0 , 1'b1 , 1'b1 , 1'b0 , 1'b1 , 1'b0 , 1'b0 , 1'b1 , 1'b0 , 1'b1
      , 1'b1 , 1'b0 , 1'b1 , 1'b0 , 1'b1 , 1'b0 , 1'b1 , 1'b0 , 1'b0 , 1'b1 , 1'b0
      , 1'b1 , 1'b1 , 1'b0 , 1'b1 , 1'b0 , 1'b0 , 1'b1 , 1'b0 , 1'b1 , 1'b0 , 1'b1
      , 1'b0 , 1'b1 , 1'b1 , 1'b0 , 1'b1 , 1'b0 , 1'b0 , 1'b1 , 1'b0 , 1'b1 , 1'b1
      , 1'b0 , 1'b1 , 1'b0 , 1'b1 , 1'b0 , 1'b1 , 1'b0 , 1'b0 , 1'b1 , 1'b0 , 1'b1
      , 1'b1 , 1'b0 , 1'b1 , 1'b0 , 1'b0 , 1'b1 , 1'b0 , 1'b1}, dataIn);
  assign realOut = {(std_Complex_base_int_std_Complex_value_int_real_mux_nl) , (std_Complex_base_int_std_Complex_value_int_real_mux_1_nl)
      , (std_Complex_base_int_std_Complex_value_int_real_mux_2_nl) , 1'b1};

  function [0:0] MUX_s_1_64_1;
    input [63:0] inputs;
    input [5:0] sel;
    reg [0:0] result;
    reg [63:0] or_inputs;
  begin
    case (sel)
      6'b000000 : begin
        result = inputs[63:63];
      end
      6'b000001 : begin
        result = inputs[62:62];
      end
      6'b000010 : begin
        result = inputs[61:61];
      end
      6'b000011 : begin
        result = inputs[60:60];
      end
      6'b000100 : begin
        result = inputs[59:59];
      end
      6'b000101 : begin
        result = inputs[58:58];
      end
      6'b000110 : begin
        result = inputs[57:57];
      end
      6'b000111 : begin
        result = inputs[56:56];
      end
      6'b001000 : begin
        result = inputs[55:55];
      end
      6'b001001 : begin
        result = inputs[54:54];
      end
      6'b001010 : begin
        result = inputs[53:53];
      end
      6'b001011 : begin
        result = inputs[52:52];
      end
      6'b001100 : begin
        result = inputs[51:51];
      end
      6'b001101 : begin
        result = inputs[50:50];
      end
      6'b001110 : begin
        result = inputs[49:49];
      end
      6'b001111 : begin
        result = inputs[48:48];
      end
      6'b010000 : begin
        result = inputs[47:47];
      end
      6'b010001 : begin
        result = inputs[46:46];
      end
      6'b010010 : begin
        result = inputs[45:45];
      end
      6'b010011 : begin
        result = inputs[44:44];
      end
      6'b010100 : begin
        result = inputs[43:43];
      end
      6'b010101 : begin
        result = inputs[42:42];
      end
      6'b010110 : begin
        result = inputs[41:41];
      end
      6'b010111 : begin
        result = inputs[40:40];
      end
      6'b011000 : begin
        result = inputs[39:39];
      end
      6'b011001 : begin
        result = inputs[38:38];
      end
      6'b011010 : begin
        result = inputs[37:37];
      end
      6'b011011 : begin
        result = inputs[36:36];
      end
      6'b011100 : begin
        result = inputs[35:35];
      end
      6'b011101 : begin
        result = inputs[34:34];
      end
      6'b011110 : begin
        result = inputs[33:33];
      end
      6'b011111 : begin
        result = inputs[32:32];
      end
      6'b100000 : begin
        result = inputs[31:31];
      end
      6'b100001 : begin
        result = inputs[30:30];
      end
      6'b100010 : begin
        result = inputs[29:29];
      end
      6'b100011 : begin
        result = inputs[28:28];
      end
      6'b100100 : begin
        result = inputs[27:27];
      end
      6'b100101 : begin
        result = inputs[26:26];
      end
      6'b100110 : begin
        result = inputs[25:25];
      end
      6'b100111 : begin
        result = inputs[24:24];
      end
      6'b101000 : begin
        result = inputs[23:23];
      end
      6'b101001 : begin
        result = inputs[22:22];
      end
      6'b101010 : begin
        result = inputs[21:21];
      end
      6'b101011 : begin
        result = inputs[20:20];
      end
      6'b101100 : begin
        result = inputs[19:19];
      end
      6'b101101 : begin
        result = inputs[18:18];
      end
      6'b101110 : begin
        result = inputs[17:17];
      end
      6'b101111 : begin
        result = inputs[16:16];
      end
      6'b110000 : begin
        result = inputs[15:15];
      end
      6'b110001 : begin
        result = inputs[14:14];
      end
      6'b110010 : begin
        result = inputs[13:13];
      end
      6'b110011 : begin
        result = inputs[12:12];
      end
      6'b110100 : begin
        result = inputs[11:11];
      end
      6'b110101 : begin
        result = inputs[10:10];
      end
      6'b110110 : begin
        result = inputs[9:9];
      end
      6'b110111 : begin
        result = inputs[8:8];
      end
      6'b111000 : begin
        result = inputs[7:7];
      end
      6'b111001 : begin
        result = inputs[6:6];
      end
      6'b111010 : begin
        result = inputs[5:5];
      end
      6'b111011 : begin
        result = inputs[4:4];
      end
      6'b111100 : begin
        result = inputs[3:3];
      end
      6'b111101 : begin
        result = inputs[2:2];
      end
      6'b111110 : begin
        result = inputs[1:1];
      end
      6'b111111 : begin
        result = inputs[0:0];
      end
      default : begin
        result = resolve_1_64(inputs);
      end
    endcase
    MUX_s_1_64_1 = result;
  end
  endfunction


  function [0:0] resolve_1_64;
    input [63:0] inputs;
    integer i, j;
    reg [0:0] rvalue;
    reg [0:0] temp1;
  begin
    resolve_1_64 = 1'bX;
    // pragma translate_off
    rvalue = inputs[0:0];
    for ( i = 1; i < 64; i = i+1 ) begin
      temp1 = inputs[( i  * 1 )-1 -: 1 ];
      rvalue = ((rvalue ~^ temp1) | 1'bX) ~^ rvalue;
    end
    resolve_1_64 = rvalue;
    // pragma translate_on
  end
  endfunction

endmodule



