% This script loads the example workspace located in Examples\Baseband
% Verification\5GAdvancedModem\3GPP_NR\NR_DL_Tx.wsv 
%
% No Baseband_Links exist in the workspace loaded below. The data created by 
% SystemVue sinks can be loaded into MATLAB from the adx file generated by 
% the analysis.
%
% The dataset (.adx file) is created in the same location as the workspace.
% If you do not have write permissions to that location this script will 
% not work. You will need to move the workspace to a writable location and 
% provide the full path of the workspace to the openWorkspace and
% openDataset functions below. To edit this file, remove the read-only
% property.

workspace = SystemVue.openWorkspace('../../../Baseband Verification/5GAdvancedModem/3GPP_NR/NR_DL_Tx.wsv');

analysis = workspace.analysis('Design1 Analysis');

analysis.param('FCarrier').value = 2e9;
analysis.param('Bandwidth').value = '50MHz';

analysis.start();

disp('Starting...')

analysis.waitForCompletion();

disp('Reading adx file...');
dataset = SystemVue.openDataset("../../../Baseband Verification/5GAdvancedModem/3GPP_NR/Design1 Analysis.adx");

N1_EVM = dataset.variables.N1_EVM;

workspace.close()
disp('Finished.')

disp(N1_EVM);

