-- ----------------------------------------------------------------------
--  HLS HDL:        VHDL Netlister
--  HLS Version:    2010a.198 Production Release
--  HLS Date:       Tue Nov  2 16:03:18 PST 2010
-- 
--  Generated by:   junakhan@PTOLEMYJK64
--  Generated date: Wed Mar 02 14:30:54 2011
-- ----------------------------------------------------------------------

-- 
-- ------------------------------------------------------------------
--  Design Unit:    Mapper
--  Generated from file(s):
--    2) $PROJECT_HOME/source/mapper.cpp
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.std_logic_arith.ALL;
USE work.funcs.ALL;
USE work.mapper_mux_pkg.ALL;


ENTITY Mapper IS
  PORT(
    dataIn : IN STD_LOGIC_VECTOR (5 DOWNTO 0);
    realOut : OUT STD_LOGIC_VECTOR (3 DOWNTO 0);
    imagOut : OUT STD_LOGIC_VECTOR (3 DOWNTO 0)
  );
END Mapper;

ARCHITECTURE v3 OF Mapper IS
  -- Default Constants

  SIGNAL std_Complex_base_int_std_Complex_value_int_imag_mux_nl : STD_LOGIC;
  SIGNAL std_Complex_base_int_std_Complex_value_int_imag_mux_1_nl : STD_LOGIC;
  SIGNAL std_Complex_base_int_std_Complex_value_int_imag_mux_2_nl : STD_LOGIC;
  SIGNAL std_Complex_base_int_std_Complex_value_int_real_mux_nl : STD_LOGIC;
  SIGNAL std_Complex_base_int_std_Complex_value_int_real_mux_1_nl : STD_LOGIC;
  SIGNAL std_Complex_base_int_std_Complex_value_int_real_mux_2_nl : STD_LOGIC;
BEGIN
  -- Default Constant Signal Assignments

  std_Complex_base_int_std_Complex_value_int_imag_mux_nl <= MUX_s_1_64_1(STD_LOGIC_VECTOR'('0'
      & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0'
      & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0'
      & '0' & '0' & '0' & '0' & '0' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1'
      & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1'
      & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1'), dataIn);
  std_Complex_base_int_std_Complex_value_int_imag_mux_1_nl <= MUX_s_1_64_1(STD_LOGIC_VECTOR'('0'
      & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '1' & '1' & '1' & '1' & '1' & '1'
      & '1' & '1' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '1' & '1' & '1'
      & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1'
      & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '1' & '1' & '1' & '1' & '1'
      & '1' & '1' & '1' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0'), dataIn);
  std_Complex_base_int_std_Complex_value_int_imag_mux_2_nl <= MUX_s_1_64_1(STD_LOGIC_VECTOR'('0'
      & '0' & '1' & '1' & '0' & '0' & '1' & '1' & '1' & '1' & '0' & '0' & '1' & '1'
      & '0' & '0' & '0' & '0' & '1' & '1' & '0' & '0' & '1' & '1' & '1' & '1' & '0'
      & '0' & '1' & '1' & '0' & '0' & '1' & '1' & '0' & '0' & '1' & '1' & '0' & '0'
      & '0' & '0' & '1' & '1' & '0' & '0' & '1' & '1' & '1' & '1' & '0' & '0' & '1'
      & '1' & '0' & '0' & '0' & '0' & '1' & '1' & '0' & '0' & '1' & '1'), dataIn);
  imagOut <= STD_LOGIC_VECTOR'((std_Complex_base_int_std_Complex_value_int_imag_mux_nl)
      & (std_Complex_base_int_std_Complex_value_int_imag_mux_1_nl) & (std_Complex_base_int_std_Complex_value_int_imag_mux_2_nl)
      & '1');
  std_Complex_base_int_std_Complex_value_int_real_mux_nl <= MUX_s_1_64_1(STD_LOGIC_VECTOR'('0'
      & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0'
      & '0' & '0' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1'
      & '1' & '1' & '1' & '1' & '1' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0'
      & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '1' & '1' & '1' & '1' & '1'
      & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1'), dataIn);
  std_Complex_base_int_std_Complex_value_int_real_mux_1_nl <= MUX_s_1_64_1(STD_LOGIC_VECTOR'('0'
      & '0' & '0' & '0' & '1' & '1' & '1' & '1' & '0' & '0' & '0' & '0' & '1' & '1'
      & '1' & '1' & '1' & '1' & '1' & '1' & '0' & '0' & '0' & '0' & '1' & '1' & '1'
      & '1' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '1' & '1' & '1' & '1'
      & '0' & '0' & '0' & '0' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '1' & '0'
      & '0' & '0' & '0' & '1' & '1' & '1' & '1' & '0' & '0' & '0' & '0'), dataIn);
  std_Complex_base_int_std_Complex_value_int_real_mux_2_nl <= MUX_s_1_64_1(STD_LOGIC_VECTOR'('0'
      & '1' & '0' & '1' & '1' & '0' & '1' & '0' & '0' & '1' & '0' & '1' & '1' & '0'
      & '1' & '0' & '1' & '0' & '1' & '0' & '0' & '1' & '0' & '1' & '1' & '0' & '1'
      & '0' & '0' & '1' & '0' & '1' & '0' & '1' & '0' & '1' & '1' & '0' & '1' & '0'
      & '0' & '1' & '0' & '1' & '1' & '0' & '1' & '0' & '1' & '0' & '1' & '0' & '0'
      & '1' & '0' & '1' & '1' & '0' & '1' & '0' & '0' & '1' & '0' & '1'), dataIn);
  realOut <= STD_LOGIC_VECTOR'((std_Complex_base_int_std_Complex_value_int_real_mux_nl)
      & (std_Complex_base_int_std_Complex_value_int_real_mux_1_nl) & (std_Complex_base_int_std_Complex_value_int_real_mux_2_nl)
      & '1');
END v3;



