-- ----------------------------------------------------------------------
--  HLS HDL:        VHDL Netlister
--  HLS Version:    2010a.198 Production Release
--  HLS Date:       Tue Nov  2 16:03:18 PST 2010
-- 
--  Generated by:   junakhan@PTOLEMYJK64
--  Generated date: Wed Mar 02 14:30:55 2011
-- ----------------------------------------------------------------------

-- 
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.std_logic_arith.ALL;
USE work.funcs.ALL;

PACKAGE Mapper_mux_pkg IS 
  FUNCTION MUX_s_1_64_1(inputs : STD_LOGIC_VECTOR(63 DOWNTO 0); sel : STD_LOGIC_VECTOR(5
      DOWNTO 0))
    RETURN STD_LOGIC;
END Mapper_mux_pkg;

PACKAGE BODY Mapper_mux_pkg IS
FUNCTION MUX_s_1_64_1(inputs : STD_LOGIC_VECTOR(63 DOWNTO 0); sel : STD_LOGIC_VECTOR(5
    DOWNTO 0))
RETURN STD_LOGIC IS
  VARIABLE or_inputs : STD_LOGIC_VECTOR(63 DOWNTO 0);
  VARIABLE result : STD_LOGIC;
  VARIABLE tmp : STD_LOGIC;
  VARIABLE result_new : STD_LOGIC;

  BEGIN
    CASE sel IS
      WHEN "111111" =>
        result := TO_STDLOGIC(inputs(0 DOWNTO 0));
      WHEN "111110" =>
        result := TO_STDLOGIC(inputs(1 DOWNTO 1));
      WHEN "111101" =>
        result := TO_STDLOGIC(inputs(2 DOWNTO 2));
      WHEN "111100" =>
        result := TO_STDLOGIC(inputs(3 DOWNTO 3));
      WHEN "111011" =>
        result := TO_STDLOGIC(inputs(4 DOWNTO 4));
      WHEN "111010" =>
        result := TO_STDLOGIC(inputs(5 DOWNTO 5));
      WHEN "111001" =>
        result := TO_STDLOGIC(inputs(6 DOWNTO 6));
      WHEN "111000" =>
        result := TO_STDLOGIC(inputs(7 DOWNTO 7));
      WHEN "110111" =>
        result := TO_STDLOGIC(inputs(8 DOWNTO 8));
      WHEN "110110" =>
        result := TO_STDLOGIC(inputs(9 DOWNTO 9));
      WHEN "110101" =>
        result := TO_STDLOGIC(inputs(10 DOWNTO 10));
      WHEN "110100" =>
        result := TO_STDLOGIC(inputs(11 DOWNTO 11));
      WHEN "110011" =>
        result := TO_STDLOGIC(inputs(12 DOWNTO 12));
      WHEN "110010" =>
        result := TO_STDLOGIC(inputs(13 DOWNTO 13));
      WHEN "110001" =>
        result := TO_STDLOGIC(inputs(14 DOWNTO 14));
      WHEN "110000" =>
        result := TO_STDLOGIC(inputs(15 DOWNTO 15));
      WHEN "101111" =>
        result := TO_STDLOGIC(inputs(16 DOWNTO 16));
      WHEN "101110" =>
        result := TO_STDLOGIC(inputs(17 DOWNTO 17));
      WHEN "101101" =>
        result := TO_STDLOGIC(inputs(18 DOWNTO 18));
      WHEN "101100" =>
        result := TO_STDLOGIC(inputs(19 DOWNTO 19));
      WHEN "101011" =>
        result := TO_STDLOGIC(inputs(20 DOWNTO 20));
      WHEN "101010" =>
        result := TO_STDLOGIC(inputs(21 DOWNTO 21));
      WHEN "101001" =>
        result := TO_STDLOGIC(inputs(22 DOWNTO 22));
      WHEN "101000" =>
        result := TO_STDLOGIC(inputs(23 DOWNTO 23));
      WHEN "100111" =>
        result := TO_STDLOGIC(inputs(24 DOWNTO 24));
      WHEN "100110" =>
        result := TO_STDLOGIC(inputs(25 DOWNTO 25));
      WHEN "100101" =>
        result := TO_STDLOGIC(inputs(26 DOWNTO 26));
      WHEN "100100" =>
        result := TO_STDLOGIC(inputs(27 DOWNTO 27));
      WHEN "100011" =>
        result := TO_STDLOGIC(inputs(28 DOWNTO 28));
      WHEN "100010" =>
        result := TO_STDLOGIC(inputs(29 DOWNTO 29));
      WHEN "100001" =>
        result := TO_STDLOGIC(inputs(30 DOWNTO 30));
      WHEN "100000" =>
        result := TO_STDLOGIC(inputs(31 DOWNTO 31));
      WHEN "011111" =>
        result := TO_STDLOGIC(inputs(32 DOWNTO 32));
      WHEN "011110" =>
        result := TO_STDLOGIC(inputs(33 DOWNTO 33));
      WHEN "011101" =>
        result := TO_STDLOGIC(inputs(34 DOWNTO 34));
      WHEN "011100" =>
        result := TO_STDLOGIC(inputs(35 DOWNTO 35));
      WHEN "011011" =>
        result := TO_STDLOGIC(inputs(36 DOWNTO 36));
      WHEN "011010" =>
        result := TO_STDLOGIC(inputs(37 DOWNTO 37));
      WHEN "011001" =>
        result := TO_STDLOGIC(inputs(38 DOWNTO 38));
      WHEN "011000" =>
        result := TO_STDLOGIC(inputs(39 DOWNTO 39));
      WHEN "010111" =>
        result := TO_STDLOGIC(inputs(40 DOWNTO 40));
      WHEN "010110" =>
        result := TO_STDLOGIC(inputs(41 DOWNTO 41));
      WHEN "010101" =>
        result := TO_STDLOGIC(inputs(42 DOWNTO 42));
      WHEN "010100" =>
        result := TO_STDLOGIC(inputs(43 DOWNTO 43));
      WHEN "010011" =>
        result := TO_STDLOGIC(inputs(44 DOWNTO 44));
      WHEN "010010" =>
        result := TO_STDLOGIC(inputs(45 DOWNTO 45));
      WHEN "010001" =>
        result := TO_STDLOGIC(inputs(46 DOWNTO 46));
      WHEN "010000" =>
        result := TO_STDLOGIC(inputs(47 DOWNTO 47));
      WHEN "001111" =>
        result := TO_STDLOGIC(inputs(48 DOWNTO 48));
      WHEN "001110" =>
        result := TO_STDLOGIC(inputs(49 DOWNTO 49));
      WHEN "001101" =>
        result := TO_STDLOGIC(inputs(50 DOWNTO 50));
      WHEN "001100" =>
        result := TO_STDLOGIC(inputs(51 DOWNTO 51));
      WHEN "001011" =>
        result := TO_STDLOGIC(inputs(52 DOWNTO 52));
      WHEN "001010" =>
        result := TO_STDLOGIC(inputs(53 DOWNTO 53));
      WHEN "001001" =>
        result := TO_STDLOGIC(inputs(54 DOWNTO 54));
      WHEN "001000" =>
        result := TO_STDLOGIC(inputs(55 DOWNTO 55));
      WHEN "000111" =>
        result := TO_STDLOGIC(inputs(56 DOWNTO 56));
      WHEN "000110" =>
        result := TO_STDLOGIC(inputs(57 DOWNTO 57));
      WHEN "000101" =>
        result := TO_STDLOGIC(inputs(58 DOWNTO 58));
      WHEN "000100" =>
        result := TO_STDLOGIC(inputs(59 DOWNTO 59));
      WHEN "000011" =>
        result := TO_STDLOGIC(inputs(60 DOWNTO 60));
      WHEN "000010" =>
        result := TO_STDLOGIC(inputs(61 DOWNTO 61));
      WHEN "000001" =>
        result := TO_STDLOGIC(inputs(62 DOWNTO 62));
      WHEN "000000" =>
        result := TO_STDLOGIC(inputs(63 DOWNTO 63));
      WHEN others =>
        result := 'X';
        -- pragma translate_off
        result_new := '1';
        FOR i IN 0 TO 63 LOOP
          IF ( result_new = '1' ) THEN
            result := TO_STDLOGIC(inputs((i+1)*1-1 DOWNTO i*1));
            result_new := '0';
          ELSE
            result := resolved(result & TO_STDLOGIC(inputs((i+1)*1-1 DOWNTO i*1)));
          END IF;
        END LOOP;
        -- pragma translate_on
    END CASE;
  RETURN result;
END;

END Mapper_mux_pkg;


