-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2014.2
-- Copyright (C) 2014 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use IEEE.std_logic_unsigned.all;

entity FIFO_demod_mux_18_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    DataIn_0_re_V_TDATA : IN STD_LOGIC_VECTOR (17 downto 0);
    DataIn_0_re_V_TVALID : IN STD_LOGIC;
    DataIn_0_re_V_TREADY : OUT STD_LOGIC;
    DataIn_1_re_V_TDATA : IN STD_LOGIC_VECTOR (17 downto 0);
    DataIn_1_re_V_TVALID : IN STD_LOGIC;
    DataIn_1_re_V_TREADY : OUT STD_LOGIC;
    DataIn_0_im_V_TDATA : IN STD_LOGIC_VECTOR (17 downto 0);
    DataIn_0_im_V_TVALID : IN STD_LOGIC;
    DataIn_0_im_V_TREADY : OUT STD_LOGIC;
    DataIn_1_im_V_TDATA : IN STD_LOGIC_VECTOR (17 downto 0);
    DataIn_1_im_V_TVALID : IN STD_LOGIC;
    DataIn_1_im_V_TREADY : OUT STD_LOGIC;
    DataOut_0_V_re_V_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    DataOut_0_V_re_V_TVALID : OUT STD_LOGIC;
    DataOut_0_V_re_V_TREADY : IN STD_LOGIC;
    DataOut_1_V_re_V_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    DataOut_1_V_re_V_TVALID : OUT STD_LOGIC;
    DataOut_1_V_re_V_TREADY : IN STD_LOGIC;
    DataOut_0_V_im_V_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    DataOut_0_V_im_V_TVALID : OUT STD_LOGIC;
    DataOut_0_V_im_V_TREADY : IN STD_LOGIC;
    DataOut_1_V_im_V_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    DataOut_1_V_im_V_TVALID : OUT STD_LOGIC;
    DataOut_1_V_im_V_TREADY : IN STD_LOGIC );
end FIFO_demod_mux_18_3;


architecture behav of FIFO_demod_mux_18_3 is 
    
    constant demod_start_position : STD_LOGIC_VECTOR (11 downto 0) := X"C01";    -- 3073
    
    signal FIFO_OutData0 : std_logic_vector(35 downto 0);
    signal FIFO_OutData1 : std_logic_vector(35 downto 0);
    signal FIFO_InData0 : std_logic_vector(35 downto 0);
    signal FIFO_InData1 : std_logic_vector(35 downto 0);
    signal FIFO_full0 : std_logic;
    signal FIFO_full1 : std_logic;
    signal FIFO_empty0 : std_logic;
    signal FIFO_empty1 : std_logic;
    signal FIFO_full0_n : std_logic;
    signal FIFO_full1_n : std_logic;
    signal FIFO_empty0_n : std_logic;
    signal FIFO_empty1_n : std_logic;
    signal FIFO_RdEn0 : std_logic;
    signal FIFO_RdEn1 : std_logic;
    signal demod_InData0_I : std_logic_vector(23 downto 0);
    signal demod_InData0_Q : std_logic_vector(23 downto 0);
    signal demod_InData1_I : std_logic_vector(23 downto 0);
    signal demod_InData1_Q : std_logic_vector(23 downto 0);
    signal demod_start_cnt : std_logic_vector(11 downto 0);
    signal demod_start : std_logic;
    signal srst : std_logic;

    component demod_mux IS
    port (
        ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    DataIn_0_re_V_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    DataIn_0_re_V_TVALID : IN STD_LOGIC;
    DataIn_0_re_V_TREADY : OUT STD_LOGIC;
    DataIn_1_re_V_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    DataIn_1_re_V_TVALID : IN STD_LOGIC;
    DataIn_1_re_V_TREADY : OUT STD_LOGIC;
    DataIn_0_im_V_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    DataIn_0_im_V_TVALID : IN STD_LOGIC;
    DataIn_0_im_V_TREADY : OUT STD_LOGIC;
    DataIn_1_im_V_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    DataIn_1_im_V_TVALID : IN STD_LOGIC;
    DataIn_1_im_V_TREADY : OUT STD_LOGIC;
    DataOut_0_V_re_V_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    DataOut_0_V_re_V_TVALID : OUT STD_LOGIC;
    DataOut_0_V_re_V_TREADY : IN STD_LOGIC;
    DataOut_1_V_re_V_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    DataOut_1_V_re_V_TVALID : OUT STD_LOGIC;
    DataOut_1_V_re_V_TREADY : IN STD_LOGIC;
    DataOut_0_V_im_V_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    DataOut_0_V_im_V_TVALID : OUT STD_LOGIC;
    DataOut_0_V_im_V_TREADY : IN STD_LOGIC;
    DataOut_1_V_im_V_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    DataOut_1_V_im_V_TVALID : OUT STD_LOGIC;
    DataOut_1_V_im_V_TREADY : IN STD_LOGIC );
    end component;

  component fifo_generator_v9_3 is
  PORT (
    clk : IN STD_LOGIC;
    srst : IN STD_LOGIC;
    din : IN STD_LOGIC_VECTOR(35 DOWNTO 0);
    wr_en : IN STD_LOGIC;
    rd_en : IN STD_LOGIC;
    dout : OUT STD_LOGIC_VECTOR(35 DOWNTO 0);
    full : OUT STD_LOGIC;
    empty : OUT STD_LOGIC
  );
  end component;

begin
  DataIn_0_re_V_TREADY <= not FIFO_full0;
  DataIn_0_im_V_TREADY <= not FIFO_full0;
  DataIn_1_re_V_TREADY <= not FIFO_full1;
  DataIn_1_im_V_TREADY <= not FIFO_full1;
  
  demod_InData0_I <= "000000" & FIFO_OutData0(17 downto 0);
  demod_InData0_Q <= "000000" & FIFO_OutData0(35 downto 18);
  demod_InData1_I <= "000000" & FIFO_OutData1(17 downto 0);
  demod_InData1_Q <= "000000" & FIFO_OutData1(35 downto 18);

  FIFO_full0_n <= not FIFO_full0;
  FIFO_full1_n <= not FIFO_full1;
  FIFO_empty0_n <= not FIFO_empty0;
  FIFO_empty1_n <= not FIFO_empty1;
  
  srst <= not ap_rst_n;
  
  FIFO_InData0 <= DataIn_0_im_V_TDATA & DataIn_0_re_V_TDATA;
  FIFO_InData1 <= DataIn_1_im_V_TDATA & DataIn_1_re_V_TDATA;

  process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n = '0') then
                demod_start_cnt <= (others => '0');
                demod_start <= '0';
            else
                if(DataIn_0_re_V_TVALID = '1') then
                    if(demod_start_cnt = X"DFF") then
                        demod_start_cnt <= (others => '0');
                    else
                    	demod_start_cnt <= demod_start_cnt + '1';
                    end if;
                end if;
                
                if(demod_start_cnt = demod_start_position) then
                    demod_start <= '1';
                else
                    demod_start <= '0';
                end if;
            end if;
        end if;
    end process;

  inst_fifo_0 : fifo_generator_v9_3
  PORT MAP (
    clk => ap_clk,
    srst => srst,
    din => FIFO_InData0,
    wr_en => DataIn_0_re_V_TVALID,
    rd_en => FIFO_RdEn0,
    dout => FIFO_OutData0,
    full => FIFO_full0,
    empty => FIFO_empty0
  );
  
  inst_fifo_1 : fifo_generator_v9_3
  PORT MAP (
    clk => ap_clk,
    srst => srst,
    din => FIFO_InData1,
    wr_en => DataIn_1_re_V_TVALID,
    rd_en => FIFO_RdEn1,
    dout => FIFO_OutData1,
    full => FIFO_full1,
    empty => FIFO_empty1
  );
  
    inst_demod_mux : demod_mux
    port map (
        ap_clk => ap_clk,
    ap_rst_n => ap_rst_n,
    ap_start => demod_start,
    ap_done => open,
    ap_idle => open,
    ap_ready => open,
    DataIn_0_re_V_TDATA => demod_InData0_I,
    DataIn_0_re_V_TVALID => FIFO_empty0_n,
    DataIn_0_re_V_TREADY => FIFO_RdEn0,
    DataIn_1_re_V_TDATA => demod_InData1_I,
    DataIn_1_re_V_TVALID => FIFO_empty1_n,
    DataIn_1_re_V_TREADY => FIFO_RdEn1,
    DataIn_0_im_V_TDATA => demod_InData0_Q,
    DataIn_0_im_V_TVALID => FIFO_empty0_n,
    DataIn_0_im_V_TREADY => open,
    DataIn_1_im_V_TDATA => demod_InData1_Q,
    DataIn_1_im_V_TVALID => FIFO_empty1_n,
    DataIn_1_im_V_TREADY => open,
    DataOut_0_V_re_V_TDATA => DataOut_0_V_re_V_TDATA,
    DataOut_0_V_re_V_TVALID => DataOut_0_V_re_V_TVALID,
    DataOut_0_V_re_V_TREADY => DataOut_0_V_re_V_TREADY,
    DataOut_1_V_re_V_TDATA => DataOut_1_V_re_V_TDATA,
    DataOut_1_V_re_V_TVALID => DataOut_1_V_re_V_TVALID,
    DataOut_1_V_re_V_TREADY => DataOut_1_V_re_V_TREADY,
    DataOut_0_V_im_V_TDATA => DataOut_0_V_im_V_TDATA,
    DataOut_0_V_im_V_TVALID => DataOut_0_V_im_V_TVALID,
    DataOut_0_V_im_V_TREADY => DataOut_0_V_im_V_TREADY,
    DataOut_1_V_im_V_TDATA => DataOut_1_V_im_V_TDATA,
    DataOut_1_V_im_V_TVALID => DataOut_1_V_im_V_TVALID,
    DataOut_1_V_im_V_TREADY => DataOut_1_V_im_V_TREADY );
  
end behav;
